[project]
name = "cardinalsbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "dotenv>=0.9.9",
    "jishaku>=2.7.5",
    "openai>=3.8.0",
    "requests>=2.34.2",
    "termcolor>=3.3.0",
]

[project.scripts]
cardinalsbot = "cardinalsbot:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
